---

- name: MariaDB server is installed
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySql
    dbservice: mariadb
    resources_url: http://materials.example.com/labs/control-handlers
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf

  tasks:
    - name: " {{ db_packages }} are installed"
      yum:
        name: "{{ db_packages }}"
        state: present
      notify:
        - set db password

    - name: Make sure the database service is running
      service: 
        name: "{{ dbservice }}"
        state: started
        enabled: true

    - name: The {{ config_file_dst }} file has been installed
      get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: yes
        notify:
          - restart db service

  handlers:
    - name: restart db service
      service: 
        name: "{{ dbservice }}"
        state: restarted

    - name: set db password
      mysql_user: 
        name: root
        password: redhat

        